name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install API deps
        working-directory: api
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Build (noop static)
        run: echo "No build step for static assets"

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SKY_058AA821E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "/"
        env:
          STORAGE_ACCOUNT_BLOB_URL: https://madeenasaad467c.blob.core.windows.net
          STORAGE_CONTAINER: content
          STORAGE_BLOB: prayer-times.json